### PR TITLE
Clearing all previous localstorage

### PR DESCRIPTION
**Pull request by bhatiadheeraj**

### CODE REVIEW

**Comment by soichih** [comment]
We don't want to remove all localStorage as we store other things in there.

**Comment by bhatiadheeraj** [comment]
do you think now we can move all these project.id.lastOpened to a data structure ? and that we can delete?

**Comment by soichih** [comment]
Why do you think that deleting it will fix the problem?

**Comment by bhatiadheeraj** [comment]
because when I logged in it used the local storage lastopenedids when firsttime property wasn't there and ended up showing me recent projects even though I logged in as well as created an account for the very firsttime.

**Pull request closed without merging**
