### PR TITLE
Fix: one more

### PR DESCRIPTION
**Pull request by anibalsolon**

### CODE REVIEW

**Comment by soichih** [comment]
I don't know why so many of the same typo!!

**Comment by francopestilli** [comment]
:-)

**Comment by anibalsolon** [comment]
The "Registerd" looks more like a copy-paste thing, they are hard to catch with the font-face used in BL

**Comment by soichih** [comment]
well at least I don't see any other instances of it :)

we also need to update a lot of "datasets" to either just "data" or "data objects" depending on the context.

**Pull request merged**
